// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class Main {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void itShowProductDetailWhenClick() {
        driver.get("http://localhost:3000/");
        // Click dismiss onboarding popup
        driver.findElement(By.xpath("//*[@id=\"mat-dialog-0\"]/app-welcome-banner/div/div[2]/button[2]")).click();

        // Click card
        driver.findElement(By.cssSelector(".mat-grid-tile:nth-child(2) .ng-star-inserted")).click();
        // Expect to show dialog
        {
            List<WebElement> elements = driver.findElements(By.cssSelector("app-product-details"));
            assert(elements.size() > 0);
        }
    }
}
